"""v3/benign.py -- the benign changes and the 4-feature surface check (P3; D8.benign; T24).

Draft S8, Table 1: "620 benign carrier modifications generated to match poisoning events
on surface statistics (edit size, embedding shift, recency, provenance shape), verified by
a two-sample test that a discriminator trained on surface features achieves AUC <= 0.56."
sentinel-v3.md S8, row "Thay doi lanh": generate exactly 620, check exactly the 4 features;
if the check fails, print "khong dat" and never relax the ceiling (L0).

T24 DEVIATIONS (L1), declared before the rerun in
docs/preregistration/lech-chuan-P3-benign.md (DEVIATION_REF):
    D-v3-2  V3_PER_EVENT = 1 control per event instead of v2's PER_EVENT = 4.  A deviation
            from v2's convention, not from the draft (the draft does not say how many
            controls an event gets).  The AUC's CI is bound by the SMALLER class, so 4:1
            spends the sample on the class that does not limit the interval: at 620 the
            criterion's floor is 0.5805 > 0.56 even for a perfectly matched corpus.  Events
            per Delta = min over Delta of candidates[Delta] // V3_PER_EVENT (Delta = 8 has
            160), balanced over the five Deltas: 800 events and 800 benign changes, NOT the
            draft's 620 (N_BENIGN_DRAFT is recorded beside it).
    D-v3-3  the payload's length is drawn from the length distribution of v3's own drift
            on dev (v3/payload.py, `draw_length`), not v2's constant 63.  The background
            is `length_background(runs)`: len(content) of every drift change of the pool
            (forced drift on CARRIER over every dev workflow), the population the
            controls are drawn from.  One draw per placement, seeded from SEED and the
            placement.  build.PAYLOAD_LENGTH and the drift process are untouched.

WHAT IS REUSED FROM v2 (analysis/benign_corpus.py, analysis/discriminator.py,
analysis/gate2_v2.py), unchanged and imported, never patched:
    PER_EVENT = 4 controls per poisoning event (v2's contract, recorded; T24 uses
    V3_PER_EVENT, see above), no reuse of a control,
    CARRIER = "memory" (v2's declared scope), SEED, the age matching (a control is read at
    now = created_at + age, so its recency equals the payload's), the per-repo control
    pool, the split protocol (discriminator.SPLIT_SEEDS = 20 train/test splits, test
    fraction 0.4, logistic regression by the same gradient descent, Hanley-McNeil CI95),
    and the criterion pinned by gate2_v2.record(): the MEAN of the CI95 upper bounds over
    the split seeds must be <= ceiling = 0.56.  (v2's 620 / 4 = 155 events was the first
    P3 run; T24 replaces it, see above.)

WHERE v3's ITEM REPRESENTATION DIFFERS FROM v2, AND WHAT IS DONE ABOUT IT
    1. The payload.  v2's corpus scored attacks.MatchedAttack (payload written to look
       like the agent's note, provenance "agent/notes").  v3's attacker writes v2's
       build.inject payload (v3/payload.py: "byte for byte"), with provenance
       "repo/docs/conventions.md", at a sleeper placement from plan_sleeper_all (C8).
    2. The benign class.  v2 matched the payload against the agent's own memory notes.
       In v3 a benign CHANGE is what the draft's drift process writes (S4: "A latent
       process independently modifies carriers benignly at rate beta"): v3/agent.py step
       6, world_v2.drift_content on a future task's topic, entering through repository
       ingress with the payload's provenance.  Here the change is GENERATED by the agent's
       own drift rule: the agent is run with drift rate 1 on the carrier (the coin always
       fires; the topic draw is the same draw, so where the nominal coin fires the item is
       byte-identical to the nominal drift item -- tested), one change per (dev workflow,
       task).  The agent notes stay as a DIAGNOSTIC control class (`v2-notes`).
    3. The features.  v2 scored F_match = {size, depth, recency, derived, topic}
       (core.Item.surface).  The draft names four: FEATURES below.
           edit_size         len(content)                              (= v2 size)
           embedding_shift   1 - cos(e_before, e_before + e_item): e is the bag of topic
                             tokens (retrieval.as_topic -- the world's semantic space) of
                             the carrier's items written at earlier tasks of the nominal
                             run; 1.0 when the carrier was empty.  L1: no embedding model.
           recency           now - created_at                          (= v2 recency)
           provenance_shape  10 * depth + derived: v2's depth (provenance path segments)
                             and derived (number of parents) as one code
       v2's own F_match on the same items is reported beside it (`surface_v2`).

DEV ONLY.  Every event and every control comes from v3.corpus.dev_workflows() (the 100 v2
workflows).  v2's benign_corpus cuts from SWEBenchDataset(pool="full"), which v3's
SECONDARY eval split is also built from, so its pool is NOT used here.  Nothing in this
module reads an eval split.

Stdlib only; imports v2, never patches it.
"""
from __future__ import annotations

import collections
import hashlib
import json
import math
import random
import statistics
from dataclasses import dataclass, field

import retrieval
from analysis import benign_corpus as B
from analysis import discriminator as DSC
from analysis import gate2_v2 as G2
from core import CarrierStore, Item, seed_of

from v3 import agent as AG
from v3 import attackers as ATK
from v3 import config as C
from v3 import corpus as K
from v3 import payload as P

# ---------------------------------------------------------------------------------------
# The declared protocol (fixed before the first run; printed into the manifest)
# ---------------------------------------------------------------------------------------

N_BENIGN_DRAFT = 620                        # the draft's number: recorded, not the target
V3_PER_EVENT = 1          # lệch chuẩn D-v3-2: xem docs/preregistration/lech-chuan-P3-benign.md
PER_EVENT = B.PER_EVENT   # giữ nguyên: quy ước v2, ghi vào record để so sánh
DEVIATION_REF = "docs/preregistration/lech-chuan-P3-benign.md"
CARRIER = B.CARRIER                         # v2's declared scope: memory
SEED = B.SEED
EPSILON = ATK.RULE_BR_EPS                   # 0.6, v3's default placement magnitude
DELTAS = tuple(C.DELTAS)                    # (0, 1, 2, 4, 8): events spread evenly
CEILING = G2.record()["ceiling"]            # 0.56 -- read, never restated
CRITERION = G2.record()["criterion"]        # mean_ci95_upper_over_split_seeds
SPLIT_SEEDS = tuple(DSC.SPLIT_SEEDS)
TEST_FRACTION = G2.record()["test_fraction"]
FEATURES = ("edit_size", "embedding_shift", "recency", "provenance_shape")
V2_FEATURES = tuple(sorted(DSC.F_MATCH))
CONTROL_KINDS = ("drift", "v2-notes")       # primary, diagnostic
PASS, FAIL = "đạt", "không đạt"

assert (PER_EVENT, V3_PER_EVENT) == (4, 1)


# ---------------------------------------------------------------------------------------
# Features
# ---------------------------------------------------------------------------------------

def _tokens(item: Item) -> collections.Counter:
    return collections.Counter(retrieval.as_topic(item.topic))


def _cos(a: collections.Counter, b: collections.Counter) -> float:
    dot = sum(v * b.get(k, 0) for k, v in a.items())
    na = math.sqrt(sum(v * v for v in a.values()))
    nb = math.sqrt(sum(v * v for v in b.values()))
    return dot / (na * nb) if na and nb else 0.0


def embedding_shift(before: list, item: Item) -> float:
    """1 - cos between the carrier's bag of topic tokens before and after `item` is added.
    `before` = the carrier's items written at earlier tasks.  Empty carrier -> 1.0."""
    e0 = collections.Counter()
    for it in before:
        e0.update(_tokens(it))
    if not e0:
        return 1.0
    e1 = e0 + _tokens(item)
    return round(1.0 - _cos(e0, e1), 12)


def provenance_shape(item: Item) -> int:
    return 10 * item.provenance.count("/") + len(item.derived_from)


def features(item: Item, now: int, shift: float) -> dict:
    """The draft's four surface statistics of `item` read at task `now`."""
    return dict(edit_size=len(item.content), embedding_shift=shift,
                recency=now - item.created_at, provenance_shape=provenance_shape(item))


# ---------------------------------------------------------------------------------------
# Runs on dev
# ---------------------------------------------------------------------------------------

def _agent(drift_rates: dict | None = None) -> AG.SleeperMockAgent:
    ag = AG.SleeperMockAgent.for_cell(C.PRIMARY, C.Cell(rho=C.RHO_GRID[0], delta=DELTAS[0]))  # rho, Delta: not read by the agent
    if drift_rates is not None:
        ag.drift_rates = dict(drift_rates)
    return ag


def run_clean(wf, drift_rates: dict | None = None):
    """The v3 agent over `wf` with no payload, seeded as the runner seeds it (rs_of)."""
    from carrier_runner import rs_of
    ag, store = _agent(drift_rates), CarrierStore()
    rs, topics = rs_of(wf, SEED), [t.topic for t in wf.tasks]
    for t, task in enumerate(wf.tasks):
        ag.run_task(t, task, store, seed=rs, marker="x", wf_topics=topics)
    return ag, store


@dataclass(frozen=True)
class Change:
    """One candidate control: an item of CARRIER written at task t of dev workflow wf_id,
    with its embedding shift in the nominal run of that workflow."""
    kind: str
    wf_id: str
    repo: str
    t: int
    item: Item
    shift: float


@dataclass
class DevRuns:
    workflows: list
    nominal: dict = field(default_factory=dict)       # wf_id -> store (nominal drift)
    pools: dict = field(default_factory=dict)         # (kind, repo) -> [Change]
    at: dict = field(default_factory=dict)            # (kind, wf_id, t) -> Change
    lengths: list = field(default_factory=list)       # D-v3-3: length_background(self)


def length_background(runs: DevRuns) -> list:
    """D-v3-3: len(content) of every drift change of the pool, sorted -- v3's
    certification background, from which the attacker draws its payload length."""
    return sorted(len(c.item.content) for (k, _), v in runs.pools.items() if k == "drift"
                  for c in v)


def _before(store, carrier: str, t: int) -> list:
    return [it for it in store.items[carrier] if it.created_at < t]


def dev_runs(workflows=None) -> DevRuns:
    """Nominal run and forced-drift run of every dev workflow; the per-repo pools."""
    wfs = K.dev_workflows() if workflows is None else list(workflows)
    out = DevRuns(workflows=wfs)
    forced = {c: 0.0 for c in AG.DRIFT_RATES}
    forced[CARRIER] = 1.0
    for wf in wfs:
        _, nominal = run_clean(wf)
        _, gen = run_clean(wf, forced)
        out.nominal[wf.wf_id] = nominal
        for kind, src, prov in (("drift", gen, AG.INGRESS_PROVENANCE),
                                ("v2-notes", nominal, "agent/notes")):
            for it in src.items[CARRIER]:
                if it.provenance != prov or it.poisoned:
                    continue
                ch = Change(kind, wf.wf_id, wf.repo, it.created_at, it,
                            embedding_shift(_before(nominal, CARRIER, it.created_at), it))
                out.pools.setdefault((kind, wf.repo), []).append(ch)
                out.at[(kind, wf.wf_id, it.created_at)] = ch
    out.lengths = length_background(out)
    return out


# ---------------------------------------------------------------------------------------
# The matched corpus
# ---------------------------------------------------------------------------------------

@dataclass(frozen=True)
class Event:
    wf_id: str
    repo: str
    delta: int
    iota: int
    sigma: int
    payload: Item
    shift: float
    controls: tuple                     # (Change, ...), V3_PER_EVENT of them
    length: int = 0                     # D-v3-3: the drawn payload length L
    length_reason: str | None = None    # N3: why the payload is not L long (tag >= L)

    def rows(self) -> tuple:
        pos = features(self.payload, self.sigma, self.shift)
        neg = [features(c.item, c.item.created_at + self.delta, c.shift)
               for c in self.controls]
        return pos, neg


def candidates(runs: DevRuns, delta: int) -> list:
    """Every feasible sleeper placement on CARRIER at `delta`, over dev, pinned order."""
    out = []
    for wf in runs.workflows:
        for sp in P.plan_sleeper_all(wf, CARRIER, delta, EPSILON):
            out.append((wf, sp))
    return out


def events_per_delta(runs: DevRuns) -> int:
    """D-v3-2: the balanced design's events per Delta, min over DELTAS of
    candidates[Delta] // V3_PER_EVENT (Delta = 8 binds)."""
    return min(len(candidates(runs, d)) // V3_PER_EVENT for d in DELTAS)


def build(runs: DevRuns | None = None, kind: str = "drift", n_events: int | None = None,
          dropped: list | None = None) -> list:
    """n_events events (default: events_per_delta(runs) per Delta), spread round-robin over
    DELTAS, each with V3_PER_EVENT distinct controls of `kind` from the same repo; no
    control is used twice in the corpus.

    Source 1 (v2's rule): the change of the host workflow written at iota = sigma - Delta,
    the one with the payload's age.  Source 2 (v2's harvest top-up): other changes of the
    same repo on dev, re-read at age Delta.  An event that cannot get V3_PER_EVENT controls
    is dropped with a reason (N3)."""
    if kind not in CONTROL_KINDS:
        raise ValueError(f"kind {kind!r} is not one of {CONTROL_KINDS}")
    runs = dev_runs() if runs is None else runs
    if n_events is None:
        n_events = events_per_delta(runs) * len(DELTAS)
    sink = dropped if dropped is not None else []
    queues = {}
    for d in DELTAS:
        cand = candidates(runs, d)
        random.Random(seed_of(SEED, "v3-benign", "events", d)).shuffle(cand)
        queues[d] = collections.deque(cand)
    quota = {d: n_events // len(DELTAS) + (i < n_events % len(DELTAS))
             for i, d in enumerate(DELTAS)}
    used, events = set(), []
    got = {d: 0 for d in DELTAS}
    while any(got[d] < quota[d] and queues[d] for d in DELTAS):
        for d in DELTAS:
            if got[d] >= quota[d] or not queues[d]:
                continue
            wf, sp = queues[d].popleft()
            ev = _match(runs, kind, wf, sp, used)
            if ev is None:
                sink.append((wf.wf_id, d, sp.iota, "fewer than V3_PER_EVENT unused controls"))
                continue
            used.update(c.item.content for c in ev.controls)
            events.append(ev)
            got[d] += 1
    for d in DELTAS:
        if got[d] < quota[d]:
            sink.append((None, d, None, f"supply: {got[d]} of {quota[d]} events"))
    return events


def _match(runs: DevRuns, kind: str, wf, sp, used: set):
    sp = sp.at_length(P.draw_length(runs.lengths, sp, SEED))
    payload = sp.item(wf)
    shift = embedding_shift(_before(runs.nominal[wf.wf_id], CARRIER, sp.iota), payload)
    controls = []
    own = runs.at.get((kind, wf.wf_id, sp.iota))
    if own is not None and own.item.content not in used:
        controls.append(own)
    spare = [c for c in runs.pools.get((kind, wf.repo), [])
             if c.item.content not in used and c is not own]
    # distinct contents only (two passes of corpus_v2 share instances)
    seen = {c.item.content for c in controls}
    uniq = []
    for c in spare:
        if c.item.content not in seen:
            seen.add(c.item.content)
            uniq.append(c)
    need = V3_PER_EVENT - len(controls)
    if len(uniq) < need:
        return None
    rng = random.Random(seed_of(SEED, "v3-benign", "ctrl", wf.wf_id, sp.iota, sp.delta))
    controls += rng.sample(uniq, need)
    return Event(wf.wf_id, wf.repo, sp.delta, sp.iota, sp.sigma, payload, shift,
                 tuple(controls), sp.length, sp.length_reason)


def rows_of(events: list) -> tuple:
    pos, neg = [], []
    for ev in events:
        p, n = ev.rows()
        pos.append(p)
        neg.extend(n)
    return pos, neg


def v2_rows_of(events: list) -> tuple:
    """v2's F_match (core.Item.surface) on the same items, read at the same `now`."""
    pos = [ev.payload.surface(now=ev.sigma) for ev in events]
    neg = [c.item.surface(now=c.item.created_at + ev.delta)
           for ev in events for c in ev.controls]
    return pos, neg


def corpus_digest(events: list) -> str:
    """sha256 over the canonical (payload, controls) record of every event, in order."""
    rec = [dict(wf=ev.wf_id, delta=ev.delta, iota=ev.iota, sigma=ev.sigma,
                payload=ev.payload.item_id,
                controls=[(c.wf_id, c.t, c.item.item_id) for c in ev.controls],
                rows=ev.rows()) for ev in events]
    return hashlib.sha256(json.dumps(rec, sort_keys=True).encode()).hexdigest()


# ---------------------------------------------------------------------------------------
# The discriminator: v2's algorithm over a declared column set
# ---------------------------------------------------------------------------------------
# discriminator._fit sizes its weights by its module-level _COLS (v2's five features), so
# it cannot score four.  This is the same algorithm (standardise over the whole sample,
# shuffle by the split seed, fit 600 steps at lr 0.3 on the first 60%, AUC and
# Hanley-McNeil on the rest) with the columns as an argument; with cols = v2's F_match it
# reproduces discriminator.auc_with_ci exactly (tested).

def _fit(X: list, y: list, ncol: int, steps: int = 600, lr: float = 0.3) -> tuple:
    w, b = [0.0] * ncol, 0.0
    for _ in range(steps):
        gw, gb = [0.0] * ncol, 0.0
        for xi, yi in zip(X, y):
            z = sum(wj * v for wj, v in zip(w, xi)) + b
            e = 1.0 / (1.0 + math.exp(-max(-30.0, min(30.0, z)))) - yi
            for j in range(ncol):
                gw[j] += e * xi[j]
            gb += e
        n = len(X)
        w = [wj - lr * g / n for wj, g in zip(w, gw)]
        b -= lr * gb / n
    return w, b


def _split(pos: list, neg: list, cols, seed: int,
           test_fraction: float = TEST_FRACTION) -> tuple:
    """(test-fold scores, test-fold labels, test-fold row indices into pos + neg, weights)
    of one declared split."""
    cols = tuple(cols)
    rows = [[float(f[c]) for c in cols] for f in pos + neg]
    y = [1.0] * len(pos) + [0.0] * len(neg)
    X = DSC._standardise(rows)
    idx = list(range(len(X)))
    random.Random(seed).shuffle(idx)
    cut = int(len(idx) * (1.0 - test_fraction))
    tr, te = idx[:cut], idx[cut:]
    w, b = _fit([X[i] for i in tr], [y[i] for i in tr], len(cols))
    sc = [sum(wj * v for wj, v in zip(w, X[i])) + b for i in te]
    lab = [y[i] for i in te]
    return sc, lab, te, w


def auc_with_ci(pos: list, neg: list, cols, seed: int,
                test_fraction: float = TEST_FRACTION) -> tuple:
    """(auc, lo, hi, weights) of one declared split."""
    sc, lab, _, w = _split(pos, neg, cols, seed, test_fraction)
    a = DSC._auc(sc, lab)
    n_pos = int(sum(lab))
    lo, hi = DSC._hanley_mcneil(a, n_pos, len(lab) - n_pos)
    return a, lo, hi, tuple(w)


def over_splits(pos: list, neg: list, cols, seeds=SPLIT_SEEDS) -> dict:
    per = {s: auc_with_ci(pos, neg, cols, s) for s in seeds}
    out = DSC.summarise_splits({s: v[:3] for s, v in per.items()}, CEILING)
    out["lo_mean"] = statistics.fmean(v[1] for v in per.values())
    out["per_seed"] = {s: tuple(round(x, 4) for x in v[:3]) for s, v in per.items()}
    out["weights_mean"] = {c: round(statistics.fmean(v[3][j] for v in per.values()), 4)
                           for j, c in enumerate(cols)}
    return out


def verdict(summary: dict) -> str:
    """The criterion gate2_v2 pins: mean CI95 upper bound over the split seeds <= 0.56."""
    return PASS if summary["hi_mean"] <= CEILING else FAIL


def floor_hi(n_pos: int, n_neg: int, test_fraction: float = TEST_FRACTION) -> float:
    """The CI95 upper bound a test fold of this corpus gives when the AUC is exactly 0.5:
    the lowest mean upper bound the criterion can see on this sample size."""
    fp, fn = round(n_pos * test_fraction), round(n_neg * test_fraction)
    return DSC._hanley_mcneil(0.5, fp, fn)[1]


def events_needed(ratio: float = 1.0, ceiling: float = CEILING,
                  test_fraction: float = TEST_FRACTION, per_event: int = V3_PER_EVENT,
                  n_max: int = 100000) -> int | None:
    """The fewest events (per_event controls each) whose floor, scaled by `ratio` (the
    design effect on the CI half-width; 1 = independent), is <= ceiling.  None when no
    n <= n_max reaches it (N3: not a number that was not found)."""
    for n in range(1, n_max + 1):
        if min(round(n * test_fraction), round(n * per_event * test_fraction)) < 2:
            continue
        if 0.5 + (floor_hi(n, n * per_event, test_fraction) - 0.5) * ratio <= ceiling:
            return n
    return None


# ---------------------------------------------------------------------------------------
# The clustered floor (T24 step 4): T17's wild cluster bootstrap, clustered by workflow
# ---------------------------------------------------------------------------------------
# floor_hi assumes independent items; events and controls cluster by workflow (django
# holds half of them).  For each split's test fold the AUC is linearised by its DeLong
# placement values (AUC - theta ~ sum_i (V10_i - AUC) / n1 + sum_j (V01_j - AUC) / n0),
# and T17's engine (v3.metrics.family_draws with Webb weights, v3.metrics.interval) draws
# the sum twice on the same seed: once with one weight per WORKFLOW (clustered), once with
# one weight per ITEM (independent).  The ratio of the two upper half-widths is the design
# effect on the interval; floor_hi_clustered = 0.5 + (floor_hi - 0.5) * mean ratio over the
# split seeds.  No new bootstrap: only the statistic fed to T17's draws is new.  numpy
# comes in with v3.metrics, imported here only.

def _placements(sc: list, lab: list) -> tuple:
    import numpy as np
    s, y = np.asarray(sc, dtype=float), np.asarray(lab, dtype=float) > 0.5
    sp, sn = s[y], s[~y]
    cmp = (sp[:, None] > sn[None, :]) + 0.5 * (sp[:, None] == sn[None, :])
    return cmp.mean(1), cmp.mean(0), float(cmp.mean())


def clustered_split(sc: list, lab: list, clusters: list, n_boot: int | None = None,
                    seed: int | None = None) -> dict:
    """One test fold: AUC, the wild-cluster (by `clusters`) and the per-item wild upper
    bounds of its 95% interval, and their half-width ratio (None if undefined, N3)."""
    import numpy as np
    from v3 import metrics as M
    n_boot = M.N_BOOT if n_boot is None else n_boot
    seed = M.BOOT_SEED if seed is None else seed
    v10, v01, auc = _placements(sc, lab)
    y = np.asarray(lab, dtype=float) > 0.5
    e = np.empty(len(lab))
    e[y] = (v10 - auc) / len(v10)
    e[~y] = (v01 - auc) / len(v01)
    names = sorted(set(clusters))
    ix = {g: i for i, g in enumerate(names)}
    eg = np.zeros(len(names))
    np.add.at(eg, [ix[g] for g in clusters], e)
    F_c = M.family_draws(len(names), n_boot, M.rng_for("wild", seed), "wild")
    F_i = M.family_draws(len(e), n_boot, M.rng_for("wild", seed), "wild")
    hi_c = M.interval(auc + F_c @ eg)[1]
    hi_i = M.interval(auc + F_i @ e)[1]
    ratio = (hi_c - auc) / (hi_i - auc) if hi_i - auc > 1e-12 else None
    return dict(auc=auc, hi_clustered=hi_c, hi_independent=hi_i, ratio=ratio,
                n_clusters=len(names))


def clusters_of(events: list) -> tuple:
    """The workflow of every row of rows_of(events): (pos clusters, neg clusters)."""
    return ([ev.wf_id for ev in events],
            [c.wf_id for ev in events for c in ev.controls])


def clustered_floor(events: list, cols=FEATURES, seeds=SPLIT_SEEDS) -> dict:
    """floor_hi_clustered and its ingredients, over the declared split seeds."""
    from v3 import metrics as M
    pos, neg = rows_of(events)
    cp, cn = clusters_of(events)
    cl = cp + cn
    per = {}
    for s in seeds:
        sc, lab, te, _ = _split(pos, neg, cols, s)
        per[s] = clustered_split(sc, lab, [cl[i] for i in te])
    ratios = [v["ratio"] for v in per.values() if v["ratio"] is not None]
    fh = floor_hi(len(pos), len(neg))
    out = dict(method="v3.metrics wild (Webb), clustered by workflow; design effect on "
                      "the CI half-width, DeLong linearisation of the test-fold AUC",
               n_boot=M.N_BOOT, boot_seed=M.BOOT_SEED,
               n_workflows=len(set(cl)), floor_hi=round(fh, 4),
               n_ratio_defined=len(ratios), n_splits=len(per),
               hi_mean_clustered=round(statistics.fmean(v["hi_clustered"]
                                                        for v in per.values()), 4),
               hi_mean_independent_boot=round(statistics.fmean(v["hi_independent"]
                                                               for v in per.values()), 4),
               per_seed={s: dict(auc=round(v["auc"], 4), hi_clustered=round(v["hi_clustered"], 4),
                                 hi_independent=round(v["hi_independent"], 4),
                                 ratio=None if v["ratio"] is None else round(v["ratio"], 4),
                                 n_clusters=v["n_clusters"])
                         for s, v in per.items()})
    if not ratios:
        out.update(ratio_mean=None, floor_hi_clustered=None, events_needed_clustered=None,
                   reason="no split has a defined half-width ratio (independent half-width 0)")
        return out
    r = statistics.fmean(ratios)
    out.update(ratio_mean=round(r, 4),
               floor_hi_clustered=round(0.5 + (fh - 0.5) * r, 4),
               events_needed_independent=events_needed(1.0),
               events_needed_clustered=events_needed(r))
    return out


# ---------------------------------------------------------------------------------------
# Per-feature diagnostics
# ---------------------------------------------------------------------------------------

def mann_whitney(pos: list, neg: list) -> float:
    return DSC._auc(pos + neg, [1] * len(pos) + [0] * len(neg))


def feature_table(pos: list, neg: list, cols) -> dict:
    out = {}
    for c in cols:
        a, b = [float(r[c]) for r in pos], [float(r[c]) for r in neg]
        sa, sb = statistics.pstdev(a), statistics.pstdev(b)
        pooled = math.sqrt((sa * sa + sb * sb) / 2) or 1.0
        auc = mann_whitney(a, b)
        out[c] = dict(auc_single=round(auc, 4), auc_single_folded=round(max(auc, 1 - auc), 4),
                      mean_pos=round(statistics.fmean(a), 4),
                      mean_neg=round(statistics.fmean(b), 4),
                      sd_pos=round(sa, 4), sd_neg=round(sb, 4),
                      smd=round((statistics.fmean(a) - statistics.fmean(b)) / pooled, 4),
                      distinct_pos=len(set(a)), distinct_neg=len(set(b)))
    return out


def _brief(s: dict) -> dict:
    return {k: (round(v, 4) if isinstance(v, float) else v)
            for k, v in s.items() if k != "per_seed"}


def measure(events: list, drop_one: bool = True, per_delta: bool = True) -> dict:
    """Everything the manifest records about one corpus."""
    pos, neg = rows_of(events)
    main = over_splits(pos, neg, FEATURES)
    out = dict(n_events=len(events), n_benign=len(neg), main=main, verdict=verdict(main),
               floor_hi=round(floor_hi(len(pos), len(neg)), 4),
               features=feature_table(pos, neg, FEATURES))
    cf = clustered_floor(events)
    out["floor_hi_clustered"] = cf["floor_hi_clustered"]
    out["clustered"] = cf
    if drop_one:
        out["drop_one"] = {}
        for c in FEATURES:
            s = over_splits(pos, neg, tuple(x for x in FEATURES if x != c))
            out["drop_one"][c] = dict(auc_median=round(s["auc_median"], 4),
                                      hi_mean=round(s["hi_mean"], 4), clear=s["clear"])
    if per_delta:
        out["per_delta"] = {}
        for d in DELTAS:
            sub = [ev for ev in events if ev.delta == d]
            if not sub:
                continue
            p, n = rows_of(sub)
            s = over_splits(p, n, FEATURES)
            out["per_delta"][d] = dict(n_events=len(sub), auc_median=round(s["auc_median"], 4),
                                       hi_mean=round(s["hi_mean"], 4), clear=s["clear"],
                                       floor_hi=round(floor_hi(len(p), len(n)), 4),
                                       verdict=verdict(s))
    return out


# ---------------------------------------------------------------------------------------
# The salt family (v2's outer criterion, gate2_v2.SALT_FAMILY): a diagnostic here
# ---------------------------------------------------------------------------------------

def salt_family(runs: DevRuns | None = None, salts=G2.SALT_FAMILY) -> dict:
    """The main check under each salt of v2's pre-registered family: the payload's topic
    subset (retrieval.SUBSET_SALT) moves the placements and the payload's tokens.  v2's
    outer rule is >= 14 of 17 salts passing; reported, never used to overturn the main
    verdict in either direction."""
    from unittest import mock
    runs = dev_runs() if runs is None else runs
    out = {}
    for salt in salts:
        with mock.patch.object(retrieval, "SUBSET_SALT", salt):
            ev = build(runs)
            pos, neg = rows_of(ev)
            s = over_splits(pos, neg, FEATURES)
        out[salt] = dict(n_events=len(ev), auc_median=round(s["auc_median"], 4),
                         hi_mean=round(s["hi_mean"], 4), clear=s["clear"], verdict=verdict(s))
    n_pass = sum(1 for v in out.values() if v["verdict"] == PASS)
    return dict(per_salt=out, passing=n_pass, total=len(out),
                rule=G2.SALT_CRITERION["rule"], required=G2.SALT_CRITERION["passing"],
                verdict=PASS if n_pass >= G2.SALT_CRITERION["passing"] else FAIL)
