"""
scoring.py -- The SCORE INTERFACE that POLICIES see.  (B0.5)

Spec: docs/thesis/eval/SPEC-Tang-Do-va-Test.md SS2.5-2.6.

This module exists because N1 changed the score scale, and all three consumers
of a score hard-coded the assumption that it lives in [0,1]:

    Policy.threshold = 0.55        -> a CLEAN 9-item carrier has P(max>0.55)=0.955
    Sentinel.observe: 1 + 2*score  -> a negative score => negative belief => the
                                      roulette wheel stops meaning anything
    default=0.0 for an empty carrier -> 0.0 is the MEDIAN of the clean distribution

Changing the scale without re-specifying the consumer side produces numbers that
cannot be traced back to a cause.  So policies do NOT see the raw score -- they
see the POSTERIOR.

THREE QUANTITIES MUST FREEZE IN THE SAME HASH CELL: pi0, the aggregation rule,
tau_sel.  Freezing them separately is meaningless -- tau_sel is computed FROM the
other two.

NOTATION -- TWO thresholds, two different objects:
    tau_det  ITEM level,    on the RAW N(0,1) score,   = z(1-phi),  manuscript SS8
    tau_sel  CARRIER level, on the POSTERIOR in [0,1], table lookup, our choice
"""
from __future__ import annotations
import functools, json, math, pathlib

import costs

#: DERIVED, not assigned: one payload among E[n_total] live items, see
#: costs.PI0_WORLD.  Kept as an import rather than a copy because
#: reference/score_table.json is generated from this same number.
PI0 = costs.PI0_WORLD
ALPHA_TASK = 0.05     # false-positive budget PER TASK (not per carrier)

_TABLE = pathlib.Path(__file__).resolve().parent / "reference" / "score_table.json"


# --------------------------------------------------------------- posterior ----

def likelihood_ratio(s: float, d_prime: float) -> float:
    """Lambda(s) = exp(d' s - d'^2/2).  Under the CLEAN hypothesis, E[Lambda] = 1 EXACTLY."""
    return math.exp(d_prime * s - d_prime * d_prime / 2.0)


def posterior(lam: float, pi0: float = PI0) -> float:
    """p = pi0 Lambda / (pi0 Lambda + 1 - pi0).

    Why a posterior rather than "derive the threshold from (d', tau_det)":
      1. the scale returns to [0,1], so threshold/observe keep their meaning;
      2. it is scale-free, so changing d' later does not break B5/B6's operating
         point;
      3. as d' -> 0, Lambda -> 1 and p -> pi0, a CONSTANT: the score loses all
         information.  That is exactly the mechanism RQ4 needs -- B5 steers by the
         score and so COLLAPSES, while Sentinel's randomisation gives it a floor
         and it degrades smoothly.
    """
    return pi0 * lam / (pi0 * lam + 1.0 - pi0)


# -------------------------------------------------- item -> carrier rollup ----

def carrier_score(raw_scores, d_prime: float, pi0: float = PI0) -> float:
    """mean-Lambda: average the LIKELIHOOD RATIOS first, then take the posterior.

    NOT max (of raw scores), because E[max_n N(0,1)] grows with n: a CLEAN 9-item
    carrier has E[max]=1.49 ~ d'_weak=1.52.  NOT noisy-OR, because it LEGITIMISES
    the confound -- a clean 20-item carrier (0.792) reads hotter than a 9-item
    carrier that actually CONTAINS the payload (0.636).  Only mean-Lambda keeps
    them apart: max(clean)=0.097 < min(poisoned)=0.128.

    An EMPTY carrier returns pi0 -- NOT YET OBSERVED, not KNOWN CLEAN.  Before D5
    this was harmless because queue/branch were always empty; after D5, empty no
    longer means safe.
    """
    lams = [likelihood_ratio(s, d_prime) for s in raw_scores]
    if not lams:
        return pi0                      # Lambda_bar = 1: no evidence
    return posterior(sum(lams) / len(lams), pi0)


# ------------------------------------------------------- table thresholds ----

def alpha_carrier(k: int, alpha_task: float = ALPHA_TASK) -> float:
    """alpha_c(K) = 1 - (1-alpha_task)^(1/K).

    Keeps FP = alpha_task PER TASK regardless of how many carriers are scored.
    With a fixed alpha_c, FP/task = 1-(1-alpha_c)^K drifts with K_t -- and the
    measured K_t rises 1.11 -> 2.00 along a workflow, while sigma lands later as
    Delta grows, so that drift runs along EXACTLY the axis RQ1 measures.
    """
    return 1.0 - (1.0 - alpha_task) ** (1.0 / k)


@functools.lru_cache(maxsize=1)
def load_table() -> dict:
    """The frozen reference table.  Generated by reference/gen_score_table.py."""
    return json.loads(_TABLE.read_text(encoding="utf-8"))


def tau_sel(n_c: int, setting: str, k: int) -> float:
    """CARRIER-SELECTION threshold: the (1 - alpha_c(K)) quantile of p_c on a CLEAN carrier.

    Indexed by BOTH n_c AND the detector setting, because the direction of the
    n-dependence REVERSES between them: weak decreases (0.299 -> 0.174), strong
    INCREASES (0.153 -> 0.246).  Holding tau fixed makes the n_c bias run in
    opposite directions on the two branches of RQ4 -- a SIGN-FLIPPING artifact,
    not a constant offset you could subtract out.
    """
    rows = load_table()["tables"][setting]["rows"]
    n = min(max(n_c, 0), len(rows) - 1)
    return rows[n]["tau_sel"][str(k)]


def expected_clean_score(n_c: int, setting: str) -> float:
    """Frozen E[p_c | clean, n] -- used for drift diagnostics."""
    rows = load_table()["tables"][setting]["rows"]
    return rows[min(max(n_c, 0), len(rows) - 1)]["mean_p"]


def bound_coefficient(setting: str, pi0: float = PI0) -> float:
    """C(d') = pi0^2 (1-pi0)(e^{d'^2} - 1) -- the coefficient of the sandwich bound.

        max(-C/n, -pi0)  <  E[p_c | clean, n] - pi0  <  0

    Right side: X^2/(1+pi0 X) > 0 POINTWISE (since 1+pi0 X = pi0 Lambda_bar + 1 - pi0 > 0)
                => pure algebra, no Jensen needed.
    Left side:  EXACTLY equivalent to E[X^3/(1+pi0 X)] >= 0.  The unweighted part
                E[X^3] = V^2(V+3)/n^2 > 0 is provable; the WEIGHT 1/(1+pi0 X)
                compresses the X>0 region and amplifies the X<0 region, so this
                is not proven.  Status: EMPIRICAL.
    """
    d = load_table()["tables"][setting]["d_prime"]
    return pi0 * pi0 * (1.0 - pi0) * (math.exp(d * d) - 1.0)


def d_prime_of(setting: str) -> float:
    return load_table()["tables"][setting]["d_prime"]
