#!/usr/bin/env python3
"""POST HOC readouts for the v2 report (after the final review, 25/09). No simulation.

1. eval-br.jsonl (260 lines, read whole): cross-fitted v_br and naive v_br per (rho, policy, Delta),
   and the BR's own N (workflows, repos).
2. eval-main.jsonl (4.5 GB, pinned): ONE streamed pass in 64 MB chunks. The sha256 of the streamed
   bytes is checked against eval-records.sha256. Only lines of the headline cell are parsed
   (setting mid, Delta in {4, 8}, B1 or Sentinel-A1, held-out attackers); the file is never loaded
   whole. Output: every (attacker, Delta) column mean for B1 and S at each rho, the column that
   decides V, its N, and how many columns sit within 0.05 of the max.
Writes posthoc.json next to this script.  From auditgame/: python3 spikes/v2/posthoc/posthoc.py
"""
import hashlib
import json
import pathlib
import time

V2 = pathlib.Path(__file__).resolve().parent.parent       # auditgame/spikes/v2 (raw records are regenerated by tools/run_draft_eval.py)
OUT = pathlib.Path(__file__).parent / "posthoc.json"
HELD_OUT = ["branch-first-write-e0.6", "memory-last-ingress-e0.3", "memory-last-write-e0.6",
            "memory-mid-write-e0.3", "queue-last-ingress-e0.6", "queue-mid-write-e0.6", "skill-last-write-e1.0"]
POLICIES = ["B1 audit-at-commit", "Sentinel-A1"]

# ---------------------------------------------------------------- 1. best response
br = {}
for line in open(V2 / "eval-br.jsonl"):
    x = json.loads(line)
    key = f"{x['rho_patch']:g}|{x['policy']}|{x['delta']}"
    br[key] = {"v_br": x["v_br"], "v_br_naive": x["v_br_naive"], "n_workflows": x["n_workflows"],
               "n_repos": len({x["repo_of"][w] for w in x["per_wf"]})}

# ---------------------------------------------------------------- 2. streamed main grid
pin = {l.split()[1]: l.split()[0] for l in (V2 / "eval-records.sha256").read_text().splitlines()
       if l and not l.startswith("#")}
NEED = (b'"setting": "mid"',)
POL = [f'"policy": "{p}"'.encode() for p in POLICIES]
DEL = (b'"delta": 4,', b'"delta": 8,')
acc = {}          # (rho, policy) -> {col: {wf: [harm...]}} in file order
repo_of = {}
h, n_lines, n_parsed, t0 = hashlib.sha256(), 0, 0, time.time()
with open(V2 / "eval-main.jsonl", "rb") as fh:
    tail = b""
    while True:
        chunk = fh.read(1 << 26)
        if not chunk:
            break
        h.update(chunk)
        lines = (tail + chunk).split(b"\n")
        tail = lines.pop()
        for ln in lines:
            n_lines += 1
            if NEED[0] not in ln or not any(p in ln for p in POL) or not any(d in ln for d in DEL):
                continue
            r = json.loads(ln)
            if r["setting"] != "mid" or r["delta"] not in (4, 8) or r["policy"] not in POLICIES \
                    or r["attack"] not in HELD_OUT:
                continue
            n_parsed += 1
            col = f"{r['attack']}@{r['delta']}"
            acc.setdefault((f"{r['rho_patch']:g}", r["policy"]), {}).setdefault(col, {}) \
               .setdefault(r["wf"], []).append(r["harm"])
            repo_of[r["wf"]] = r["repo"]
    assert tail == b"", "file does not end with a newline"
sha = h.hexdigest()
assert sha == pin["eval-main.jsonl"], f"sha256 {sha} != pin {pin['eval-main.jsonl']}"

cells = {}
for (rho, pol), cols in acc.items():
    means = {c: sum(sum(v) / len(v) for v in d.values()) / len(d) for c, d in cols.items()}
    V = max(means.values())
    dec = [c for c, m in means.items() if m == V]
    c = dec[0]
    cells[f"{rho}|{pol}"] = {
        "V": V, "deciding": dec, "n_columns": len(means),
        "n_workflows": len(cols[c]), "n_repos": len({repo_of[w] for w in cols[c]}),
        "n_episodes": sum(len(v) for v in cols[c].values()),
        "within_0.05": sum(1 for m in means.values() if m >= V - 0.05),
        "columns": {k: {"mean": m, "n_workflows": len(cols[k])} for k, m in sorted(means.items())}}

OUT.write_text(json.dumps({"sha256_eval_main": sha, "lines_streamed": n_lines, "lines_parsed": n_parsed,
                           "seconds": round(time.time() - t0, 1), "br": br, "cells": cells}, indent=1))
print(f"streamed {n_lines} lines, parsed {n_parsed}, sha256 ok, {time.time() - t0:.1f}s -> {OUT}")
for k, v in sorted(cells.items()):
    print(k, v["deciding"], round(v["V"], 4), v["n_workflows"], v["n_repos"], v["n_episodes"], "within0.05:", v["within_0.05"])
